/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opticalflow_OpticalFlow */

#ifndef _Included_com_example_opticalflow_OpticalFlow
#define _Included_com_example_opticalflow_OpticalFlow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opticalflow_OpticalFlow
 * Method:    opticalFlow
 * Signature: (JIDD)V
 */
JNIEXPORT void JNICALL Java_com_example_opticalflow_OpticalFlow_opticalFlow
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
